### ISSUE TITLE
In Linux, capitalization matters. So I propose that we have a consistent capitalization system.

### ISSUE THREAD

**Issue by koolimy2** [hyengkoo/hello-world#19]
I don't know if this would apply for all computer systems, but for Linux purposes, Koo.html is different from koo.html. I therefore propose that we keep a consistent file naming system, so that we don't run into problems in the future. What do you think is best?

**Comment by koolimy** [comment]
Maybe all lowercase?

**Comment by koolimy2** [comment]
that is OK with me.

**Comment by koolimy** [comment]
Need Dad's opinion and we are good to go

**Comment by hyengkoo** [comment]
Lower case letters seem good to me.
