### ISSUE TITLE
Proposal: edit readme.md so that it displays best practices. (Close if concluded)

### ISSUE THREAD

**Issue by koolimy2** [hyengkoo/hello-world#22]
On the issues tab we have several discussions on what may be the best practices for this repository. For instance, we had discussions regarding capitalization, the use of `<br> and </br>`, and possibly renaming file names so that they don't include spaces. 

I propose that we edit the readme.md document so that it includes some best practices. The readme.md document is the document that shows up on the front page of the repository, so anyone who wants to edit something can get a quick glance at its contents. I think it might be a good idea to add best practices to that document, so that even if we take a long break from editing this repository, we will be able to take one quick look at the readme.md and remember best practices. I also think it prevents the issues section from becoming too cluttered.

**Comment by koolimy** [comment]
I agree!

**Comment by koolimy** [comment]
Propose to delete all the superfluous stuff in issues now that we have the readme?
